# Generated by Django 5.0.1 on 2024-01-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCrypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='icon_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
